# Generated by Django 5.1.1 on 2025-11-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('residential', 'Residential Cleaning'), ('commercial', 'Commercial Cleaning'), ('deep_cleaning', 'Deep Cleaning'), ('move_in_out', 'Move In/Out Cleaning')], max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('service_frequency', models.CharField(choices=[('one_time', 'One-Time Service'), ('weekly', 'Weekly Service'), ('bi_weekly', 'Bi-Weekly Service'), ('monthly', 'Monthly Service')], max_length=50)),
                ('property_size', models.CharField(choices=[('small', 'Small (up to 1000 sqft)'), ('medium', 'Medium (1000-2500 sqft)'), ('large', 'Large (2500+ sqft)')], max_length=50)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('service', 'Service Request'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
