"""
Django settings for mezgone project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from env in production; fallback for local dev only
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-!owur-9%^f4b&2q9uot*6^5rnc$s2oy2v*k2pzm()j&7u5rd3v')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

allowed_hosts_env = os.getenv('ALLOWED_HOSTS')
allowed_hosts_set = set()

# Include explicit env-provided hosts if present (ignore unresolved placeholders)
if allowed_hosts_env:
    for h in allowed_hosts_env.split(','):
        h = h.strip()
        if h and not h.startswith('${'):
            allowed_hosts_set.add(h)

# Always include Render-provided hostname when available
render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_host:
    allowed_hosts_set.add(render_host)

# Useful defaults for health checks and local access
allowed_hosts_set.update({'127.0.0.1', 'localhost', '.onrender.com'})

ALLOWED_HOSTS = sorted(allowed_hosts_set)

# CSRF trusted origins: include exact Render hostname and wildcard for onrender.com
csrf_trusted = set()
if render_host:
    csrf_trusted.add(f"https://{render_host}")
csrf_trusted.add('https://*.onrender.com')
CSRF_TRUSTED_ORIGINS = sorted(csrf_trusted)

# Useful defaults for health checks and local access
allowed_hosts_set.update({'127.0.0.1', 'localhost', '.onrender.com'})

ALLOWED_HOSTS = sorted(allowed_hosts_set)

# CSRF trusted origins: include exact Render hostname and wildcard for onrender.com
csrf_trusted = set()
if render_host:
    csrf_trusted.add(f"https://{render_host}")
csrf_trusted.add('https://*.onrender.com')
CSRF_TRUSTED_ORIGINS = sorted(csrf_trusted)


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #installed apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mezgone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mezgone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Use absolute static URL so links resolve correctly on any path
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'templates' / 'assets',  # serve css/js from templates/assets during development
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration - serve static files directly via middleware
WHITENOISE_USE_FINDERS = True  # Serve from STATICFILES_DIRS in addition to STATIC_ROOT
WHITENOISE_AUTOREFRESH = DEBUG  # Auto-reload in development
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'tgz', 'bz2', 'tbz', 'xz', 'br', 'swf', 'flv', 'woff', 'woff2']

# Django 5.x STORAGES configuration (REQUIRED for WhiteNoise to work)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Ensure request.is_secure() works behind a proxy (Render)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
